---
- name: Install zip util
  become: yes
  package:
    name: unzip
    state: latest

- name: "Download {{ gradle_zip }}"
  get_url:
      url: "{{ gradle_download_url }}"
      dest: "{{ gradle_download_dest }}"
      checksum: "{{ gradle_checksum }}"

- name: "Unzip {{ gradle_zip }}"
  unarchive:
      src: "{{ gradle_download_dest }}"
      dest: "{{ gradle_dir }}"
      remote_src: True

- name: "Add gradle bin"
  file:
      src: "{{ gradle_dir }}/gradle-{{ gradle_version }}/bin/gradle"
      dest: "{{ gradle_bin }}"
      owner: root
      group: root
      state: link

- name: Check gradle bin
  stat:
    path: "{{ gradle_bin }}"
  register: gradle_after

- fail:
    msg: "Gradle install failed, reason: unknown"
  when: 
    gradle_after.stat.exists == False
