---
- name: Clear repo 
  file:
    path: "{{ app_repo_dir }}"
    state: absent

- name: Pull repo
  git:
    repo: "{{ app_repo }}"
    dest: "{{ app_repo_dir }}"

- name: Set repo permissions
  file:
    path: "{{ app_repo_dir }}"
    state: directory
    recurse: yes
    mode: "0755"

- name: Get app properties
  shell: /usr/local/bin/gradle properties | grep version | grep -o -E '\S+$'
  args: 
    chdir: "{{ app_repo_dir }}"
  register: app_version

- name: Gradle build
  command: /usr/local/bin/gradle bootJar
  args:
    chdir: "{{ app_repo_dir }}"

- name: Move jar
  copy:
    remote_src: True
    src: "{{ gradle_jar_dir }}/{{ app_name }}-{{ app_version.stdout }}.jar"
    dest: "{{ app_jar }}"

- name: Supervisor config
  template:
    src: app.conf.j2
    dest: "{{ supervisor_cfg_dir }}/{{ app_name }}.conf"
    